#cloud-config

# vim: syntax=yaml
#
# This is the configuration syntax that the write_files module
# will know how to understand. Encoding can be given b64 or gzip or (gz+b64).
# The content will be decoded accordingly and then written to the path that is
# provided.
#
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - openssh-server
  - git
  - make
  - fish
  - neovim
  - python3
  - python3-dev
  - python3-venv

write_files:
  - path: /root/.ssh/authorized_keys
    owner: root:root
    permissions: '0600'
    content: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDolx3LMaGMdrXCd8VIs8UDVIaRwOpEKIBCHDoPDpiv6ZxjSRIkFkpxcp5tYF6qJj/QfdmWgUuGCDO2alEy0KBU4GNr+AEewve5ca+wci/kedxHfGtxv5HYa9TmxUkZEgbwbLeku6bHJi4h8QPVgKAjxAewjpPtSip+v9wtoXXNOBxBu+Vr+4AhkZE/Rbqf0neJouLtMcnM4Y4TMa82l6U1vreDPmYlk/hyKi2zDVUkKP1VSV+lVRGmoixdvirsbFQWgflUhd7x0/ejUIVJToM6/YN0iiB7zhGg3zu7dC/IkcGVGwF/qwC7feh6BO3Z9rItu9HjHVIuV8gXWSeJOJHJ 26huitailang@chensijiandeMBP
  - path: /etc/apt/sources.list
    content: |
      # 默认注释了源码镜像以提高 apt update 速度，如有需要可自行取消注释
      deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm main contrib non-free non-free-firmware
      # deb-src https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm main contrib non-free non-free-firmware

      deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-updates main contrib non-free non-free-firmware
      # deb-src https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-updates main contrib non-free non-free-firmware

      deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-backports main contrib non-free non-free-firmware
      # deb-src https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-backports main contrib non-free non-free-firmware

      # 以下安全更新软件源包含了官方源与镜像站配置，如有需要可自行修改注释切换
      deb https://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware
      # deb-src https://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware

# 确保SSH服务启动
services:
  ssh:
    enabled: true
    ensure_running: true

runcmd:
  - |
    #!/bin/bash
    #
    # This script will be run as root on the host after the VM is created.
    #
    # This script is also run on the host when the VM is restarted.
    #
    # This script is run as root on the host.
    #
    # This script is run as root on the host.
    #
    # This script is run as root on thehost.
    chsh -s /usr/bin/fish root
    echo "fish shell set as default shell for root user"
  - |
    #!/bin/bash
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://mirrors.ustc.edu.cn/docker-ce/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
    apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-compose
